#!/bin/sh
# SWF builder wrapper
# Usage: mkswf [-w width] [-h height] [-o outfile] [-c classname] abcfiles ...
#   if -o is ommited, last abcfile name is used for output.

DIR=$(dirname $0)
TAMACC="$DIR/../cola.sh $DIR/mkswf.k"

$TAMACC $@
